// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZPDZS170BKu2GY32djWzQy1QmSrx6v0Y',
    appId: '1:61317888308:web:1d6d98be4df12a2013cd61',
    messagingSenderId: '61317888308',
    projectId: 'praktikum-pbm-tugas',
    authDomain: 'praktikum-pbm-tugas.firebaseapp.com',
    storageBucket: 'praktikum-pbm-tugas.firebasestorage.app',
    measurementId: 'G-TPM99XSVRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDqvA6XcvtPrbh14BrG_G5_CJFu6Yt7ns',
    appId: '1:61317888308:android:2725128d7118c49713cd61',
    messagingSenderId: '61317888308',
    projectId: 'praktikum-pbm-tugas',
    storageBucket: 'praktikum-pbm-tugas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-dNpGaBK4Lp8OuRgAZ80GCQ9E5umXnk',
    appId: '1:61317888308:ios:4d3da69afdcd32e413cd61',
    messagingSenderId: '61317888308',
    projectId: 'praktikum-pbm-tugas',
    storageBucket: 'praktikum-pbm-tugas.firebasestorage.app',
    iosBundleId: 'com.example.tugasPbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0-dNpGaBK4Lp8OuRgAZ80GCQ9E5umXnk',
    appId: '1:61317888308:ios:4d3da69afdcd32e413cd61',
    messagingSenderId: '61317888308',
    projectId: 'praktikum-pbm-tugas',
    storageBucket: 'praktikum-pbm-tugas.firebasestorage.app',
    iosBundleId: 'com.example.tugasPbm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZPDZS170BKu2GY32djWzQy1QmSrx6v0Y',
    appId: '1:61317888308:web:fec0f2c02e32fb4313cd61',
    messagingSenderId: '61317888308',
    projectId: 'praktikum-pbm-tugas',
    authDomain: 'praktikum-pbm-tugas.firebaseapp.com',
    storageBucket: 'praktikum-pbm-tugas.firebasestorage.app',
    measurementId: 'G-LLEVWG72EL',
  );
}
